import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Suspense} from 'react'
import Loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * @description This is the root layout for all pages.It is required by Next.js.
 */
export default function RootLayout({
  children,
  team,
  analyze,
}: {
  children: React.ReactNode,
  team:React.ReactNode,
  analyze:React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading/>}>
        main page layout
        {children}
        {team}
        {analyze}
        </Suspense>
        </body>
    </html>
  )
}
